version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./src/openapi/api:/openapi 
      - ./public:/app/public
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - ./server:/app
    networks:
      - app-network

  prism:
    image: stoplight/prism:4
    command: 'mock -h 0.0.0.0 /src/openapi/api/openapi.yaml'
    volumes:
      - ./src/openapi/api/openapi.yaml:/src/openapi/api/openapi.yaml:ro
    ports:
      - '3001:4010'

networks:
  app-network:
    driver: bridge
