// 使うProtobufのバージョン

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: src/grpc/proto/book.proto

// パッケージ名を決めてる。
// コード生成のときに名前空間の役割

package book

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ここからは「Book」というメッセージ（データ構造）を定義する部分
type Book struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 書籍のユニークID（UUID形式を想定）
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 書名
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// 著者名
	Author string `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	// 読んだ感想やメモ（任意）
	Memo string `protobuf:"bytes,4,opt,name=memo,proto3" json:"memo,omitempty"`
	// 読書状況。unread / reading / done のいずれかを文字列で管理
	Status string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	// タグやジャンルのリスト。複数あるので repeated を使う（配列）
	Tags []string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	// 読み始めた日。ISO 8601形式の日付文字列（例: 2024-04-24）
	StartedAt string `protobuf:"bytes,7,opt,name=startedAt,proto3" json:"startedAt,omitempty"`
	// 読み終えた日。ISO 8601形式の日付文字列
	FinishedAt string `protobuf:"bytes,8,opt,name=finishedAt,proto3" json:"finishedAt,omitempty"`
	// データ作成日時。システムで管理する想定
	CreatedAt     string `protobuf:"bytes,9,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_src_grpc_proto_book_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_proto_book_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_src_grpc_proto_book_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Book) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *Book) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Book) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Book) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *Book) GetFinishedAt() string {
	if x != nil {
		return x.FinishedAt
	}
	return ""
}

func (x *Book) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 1冊の本をID指定して取得するためのリクエスト
type GetBookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 取得したい本のID
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookRequest) Reset() {
	*x = GetBookRequest{}
	mi := &file_src_grpc_proto_book_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookRequest) ProtoMessage() {}

func (x *GetBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_proto_book_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookRequest.ProtoReflect.Descriptor instead.
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return file_src_grpc_proto_book_proto_rawDescGZIP(), []int{1}
}

func (x *GetBookRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 1冊の本の情報を返すレスポンス
type GetBookResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Book型のデータが1つ返る
	Book          *Book `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookResponse) Reset() {
	*x = GetBookResponse{}
	mi := &file_src_grpc_proto_book_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookResponse) ProtoMessage() {}

func (x *GetBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_proto_book_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookResponse.ProtoReflect.Descriptor instead.
func (*GetBookResponse) Descriptor() ([]byte, []int) {
	return file_src_grpc_proto_book_proto_rawDescGZIP(), []int{2}
}

func (x *GetBookResponse) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

// 複数の本の一覧を取得するためのリクエスト（今回は特に条件なし）
type ListBooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBooksRequest) Reset() {
	*x = ListBooksRequest{}
	mi := &file_src_grpc_proto_book_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBooksRequest) ProtoMessage() {}

func (x *ListBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_proto_book_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBooksRequest.ProtoReflect.Descriptor instead.
func (*ListBooksRequest) Descriptor() ([]byte, []int) {
	return file_src_grpc_proto_book_proto_rawDescGZIP(), []int{3}
}

// 複数の本の情報を返すレスポンス
type ListBooksResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Book型のリスト（配列）が返る
	Books         []*Book `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBooksResponse) Reset() {
	*x = ListBooksResponse{}
	mi := &file_src_grpc_proto_book_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBooksResponse) ProtoMessage() {}

func (x *ListBooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_proto_book_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBooksResponse.ProtoReflect.Descriptor instead.
func (*ListBooksResponse) Descriptor() ([]byte, []int) {
	return file_src_grpc_proto_book_proto_rawDescGZIP(), []int{4}
}

func (x *ListBooksResponse) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

var File_src_grpc_proto_book_proto protoreflect.FileDescriptor

const file_src_grpc_proto_book_proto_rawDesc = "" +
	"\n" +
	"\x19src/grpc/proto/book.proto\x12\x04book\"\xe0\x01\n" +
	"\x04Book\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x12\n" +
	"\x04memo\x18\x04 \x01(\tR\x04memo\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x1c\n" +
	"\tstartedAt\x18\a \x01(\tR\tstartedAt\x12\x1e\n" +
	"\n" +
	"finishedAt\x18\b \x01(\tR\n" +
	"finishedAt\x12\x1c\n" +
	"\tcreatedAt\x18\t \x01(\tR\tcreatedAt\" \n" +
	"\x0eGetBookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x0fGetBookResponse\x12\x1e\n" +
	"\x04book\x18\x01 \x01(\v2\n" +
	".book.BookR\x04book\"\x12\n" +
	"\x10ListBooksRequest\"5\n" +
	"\x11ListBooksResponse\x12 \n" +
	"\x05books\x18\x01 \x03(\v2\n" +
	".book.BookR\x05books2\x83\x01\n" +
	"\vBookService\x126\n" +
	"\aGetBook\x12\x14.book.GetBookRequest\x1a\x15.book.GetBookResponse\x12<\n" +
	"\tListBooks\x12\x16.book.ListBooksRequest\x1a\x17.book.ListBooksResponseBEZCgithub.com/haruna1256/schema-vs-code-api-comparison/proto/book;bookb\x06proto3"

var (
	file_src_grpc_proto_book_proto_rawDescOnce sync.Once
	file_src_grpc_proto_book_proto_rawDescData []byte
)

func file_src_grpc_proto_book_proto_rawDescGZIP() []byte {
	file_src_grpc_proto_book_proto_rawDescOnce.Do(func() {
		file_src_grpc_proto_book_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_grpc_proto_book_proto_rawDesc), len(file_src_grpc_proto_book_proto_rawDesc)))
	})
	return file_src_grpc_proto_book_proto_rawDescData
}

var file_src_grpc_proto_book_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_src_grpc_proto_book_proto_goTypes = []any{
	(*Book)(nil),              // 0: book.Book
	(*GetBookRequest)(nil),    // 1: book.GetBookRequest
	(*GetBookResponse)(nil),   // 2: book.GetBookResponse
	(*ListBooksRequest)(nil),  // 3: book.ListBooksRequest
	(*ListBooksResponse)(nil), // 4: book.ListBooksResponse
}
var file_src_grpc_proto_book_proto_depIdxs = []int32{
	0, // 0: book.GetBookResponse.book:type_name -> book.Book
	0, // 1: book.ListBooksResponse.books:type_name -> book.Book
	1, // 2: book.BookService.GetBook:input_type -> book.GetBookRequest
	3, // 3: book.BookService.ListBooks:input_type -> book.ListBooksRequest
	2, // 4: book.BookService.GetBook:output_type -> book.GetBookResponse
	4, // 5: book.BookService.ListBooks:output_type -> book.ListBooksResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_src_grpc_proto_book_proto_init() }
func file_src_grpc_proto_book_proto_init() {
	if File_src_grpc_proto_book_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_grpc_proto_book_proto_rawDesc), len(file_src_grpc_proto_book_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_grpc_proto_book_proto_goTypes,
		DependencyIndexes: file_src_grpc_proto_book_proto_depIdxs,
		MessageInfos:      file_src_grpc_proto_book_proto_msgTypes,
	}.Build()
	File_src_grpc_proto_book_proto = out.File
	file_src_grpc_proto_book_proto_goTypes = nil
	file_src_grpc_proto_book_proto_depIdxs = nil
}
