openapi: "3.0.3"

# API自体のメタデータを定義
info:
  # APIのタイトル
  title: "openapiのAPI"
  # APIの説明
  description: "openapiを使って作成した本のAPIです"
  # APIのバージョン
  version: "1.0.0"

servers:
  - url: "http://localhost:3001"
    description: "モックサーバー（Prism）"
  - url: "http://localhost:8080"
    description: "実サーバー"


# 全体のタグ一覧
# ここで定義されたタグは、各エンドポイント（paths内）に付けられる
tags:
  # タグの名前
  # 指定することで、「これは本関連の処理です」と分類
  - name: "books"
    # 何を意味するかの説明
    description: "本情報の操作"

# エンドポイント一覧
paths: 
  # APIのエンドポイント（パス）を定義
  "/books":
    # HTTPのメソットの定義
    get:
      # エンドポイントの簡単な説明
      # ドキュメント表示用に使用
      summary: "本の一覧の取得"
      # タグ
      tags: ["books"]
      # このAPIが非推奨（deprecated）かどうかを示す。
      # ここでは false なので、まだ正式に使えるAPI。
      deprecated: false
      # レスポンス（返却内容）を定義
      responses:
        # ステータスコード
        "200":
          # ステータスコード 200 の説明
          description: "成功"
          # レスポンスの中身（Content-Type）を定義
          content:
            # レスポンスは JSON形式 で返される
            application/json:
              # レスポンスボディのデータ構造（スキーマ）を指定
              schema:
                # スキーマ定義を再利用している
                # 参照先
                $ref: "#/components/schemas/Books"









# 特定の本の詳細取得 -> GET /books/{id}

# 本の新規登録 -> POST /books

# 特定の本の情報を更新 -> PUT /books/{id}

# 特定の本を削除 -> DELETE /books/{id}

# 特定の本をステータスでの絞り込み -> GET /books?status=done

# 特定の本をタグでの絞り込み -> GET /books?tags=小説






# OpenAPIの「部品」セクション。再利用可能な定義（スキーマ、レスポンスなど）をここにまとめる。
components:
  # スキーマ（データ構造）を定義する
  schemas:
    Books:
      # スキーマを定義、配列型として定義
      type: array
      # 配列の中身（各要素）の型を定義
      items: 
        # 各要素はオブジェクト型
        type: object
        # オブジェクトが持つプロパティ（フィールド）を定義
        properties:
          "id": {type: string, example: "a13f9c6d-b849-442a-b3d4-fb05c221d2a9"}
          "title": {type: string, example: "本のタイトル"}
          "author": {type: string, example: "著者名"}
          "memo": {type: string, example: "感想やメモ（任意）"}
          "status": {type: string, enum: [unread, reading, done], example: "unread"}
          "tags": {type: array, example: ["小説", "エッセイ"]}
          "startedAt": {type: string, format: date, example: "2024-04-24"}
          "finishdAt": {type: string, format: date, example: "2024-04-25"}
          "createdAt": {type: string, format: date, example: "2024-04-24"}
  
    
  